#Usar uma imagem base do Node.js
FROM node:14

# Instalar FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Criar diretório de trabalho
WORKDIR /app

# Copiar package.json e instalar dependências
COPY package.json ./
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]